### ISSUE TITLE
ModuleNotFoundError: No module named 'osm'

### ISSUE THREAD

**Issue by Souravonline2022** [rannof/OSM#10]
Hi,
After successful installation with pip install -r requirements.txt, Still getting error ModuleNotFoundError: No module named 'osm'

![image](https://user-images.githubusercontent.com/119504128/204800993-acb3f3fc-d065-448c-83fb-2b35179b3574.png)
 Please help, I am using windows 10

**Comment by rannof** [comment]
Please make sure the osm.py file is in your pythonpath or in the same directory as your code.
It is not a proper installer - this is an independent module file. You can simply add osm.py to your working directory/project.

**Comment by Souravonline2022** [comment]
Thanks for your support. It work now post adding it in code directory.
One Thing I need is to add scale to the map like below. can you help me with it. How to enable it.
![image](https://user-images.githubusercontent.com/119504128/204875608-3d422a4f-f3e4-4cc6-8df3-f5f8705eea8e.png)

**Comment by rannof** [comment]
This is not an issue, and not the same issue.
You can use a simple plot of line with | as symbol to have a |--------| scale. 
Calculating the required length of the line depends on your required accuracy, but can be approx as 1 deg = 111.111 m
You can set the start point of the line where you want the line to be plot and use the length to determine the end point.

Also, you can use [matplotlib_scalebar.scalebar](https://pypi.org/project/matplotlib-scalebar/) with scale/units parameters of 111.111 and m.
